name: viet_wallet
description: Flutter project final in KMA.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1

  flutter_app_badger: ^1.5.0
  equatable: ^2.0.5

  connectivity_plus: ^3.0.3

  flutter_secure_storage: ^8.0.0

  intl: ^0.17.0

  flutter_otp_text_field: ^1.1.1

  jwt_decoder: ^2.0.1

  syncfusion_flutter_charts: ^20.4.42

  flutter_datetime_picker: ^1.5.1

  flutter_localization: ^0.1.7

  currency_picker: ^2.0.13
  
  flutter_switch: ^0.3.2

  charts_flutter: ^0.12.0
  flutter_cupertino_date_picker: ^1.0.13


  #Android implementation of the local_auth plugin.
  local_auth_android: ^1.0.19

  #Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  local_auth: ^2.1.5

  #A powerful HTTP package for Dart/Flutter, which supports Global settings, Interceptors, FormData, Aborting and canceling a request, Files uploading and downloading, Requests timeout, Custom adapters, etc.
  dio: ^5.0.1

  #A cookie manager for Dio, which supports persistent cookies in RAM and file.
  dio_cookie_manager: ^2.1.1

  #A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.0.2

  #Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.2

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
